services:
  MLBackend:
    image: registry.gitlab.com/r0hi77_node/mlbackend:latest
    container_name: ml-backend
    ports:
      - "5000:5000"
    networks:
      - server_network
    volumes:
      - shared:/var/tmp
      - /var/log/MLBackend:/app/logs
    restart: unless-stopped


volumes:
  shared:

networks:
  server_network:
    driver: bridge